# Generated by Django 2.2.4 on 2020-01-11 03:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='eventgeomapdata',
            managers=[
            ],
        ),
        migrations.AlterField(
            model_name='eventgeomapdata',
            name='created_date',
            field=models.DateTimeField(auto_now_add=True, help_text='建立時間', null=True),
        ),
        migrations.AlterField(
            model_name='eventgeomapdata',
            name='event_addr',
            field=models.CharField(help_text='事件地址', max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='eventgeomapdata',
            name='event_end_time',
            field=models.DateTimeField(help_text='事件結束時間 (CST)', null=True),
        ),
        migrations.AlterField(
            model_name='eventgeomapdata',
            name='event_href',
            field=models.URLField(max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='eventgeomapdata',
            name='event_lat',
            field=models.DecimalField(decimal_places=9, max_digits=12, null=True, verbose_name='事件緯度'),
        ),
        migrations.AlterField(
            model_name='eventgeomapdata',
            name='event_lon',
            field=models.DecimalField(decimal_places=9, max_digits=12, null=True, verbose_name='事件經度'),
        ),
        migrations.AlterField(
            model_name='eventgeomapdata',
            name='event_start_time',
            field=models.DateTimeField(help_text='事件開始時間 (CST)', null=True),
        ),
        migrations.AlterField(
            model_name='eventgeomapdata',
            name='event_title',
            field=models.CharField(help_text='事件名稱', max_length=256, null=True),
        ),
    ]
