# Generated by Django 2.2.4 on 2020-01-16 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0002_auto_20200111_1109'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClientJobs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_name', models.CharField(help_text='任務名稱', max_length=256, null=True)),
                ('cron_regex', models.CharField(help_text='執行時間規則', max_length=256, null=True)),
                ('next_time', models.DateTimeField(help_text='下次執行時間', null=True)),
            ],
        ),
    ]
